#spring.application.name= Service-Registry
#server.port=8761
#
#
##name of this service
#eureka.instance.hostname = localhost
#
##this will prevent to fetch registry
#eureka.client.fetch-registry=false
##this will prevent this module to register as a client.
#eureka.client.register-with-eureka=false